name: encrypt
version: 4.1.0
description: A set of high-level APIs over PointyCastle for two-way cryptography.
author: leocavalcante <lc@leocavalcante.com>
homepage: https://github.com/leocavalcante/encrypt

executables:
  secure-random:

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  args: ^2.0.0
  asn1lib: ^1.0.0
  clock: ^1.1.0
  collection: ^1.15.0
  crypto: ^3.0.0
  pointycastle: ^2.0.1

dev_dependencies:
  test: ^1.16.8
